name: sync-lxk0301/jd_scripts

on:
  schedule:
  - cron:  "*/15 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    if: ${{ github.event.repository.owner.id == github.event.sender.id  }}
    timeout-minutes: 2

    steps:
    - name: Init Build Dependencies
      env:
        PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E rm -rf /etc/apt/sources.list.d
        sudo -E apt-get update -y
        sudo -E apt-get install -y build-essential git git-core curl wget
        sudo -E apt-get clean -y
        git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'

    - name: Prepare
      run: |
        mkdir -p ~/.ssh
        echo -e "${{ secrets.LXKEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitee.com > ~/.ssh/known_hosts
    - uses: actions/checkout@v2
      with:
          persist-credentials: false
    - name: sync LXK9301-scripts
      uses: repo-sync/github-sync@v2
      if: env.PAT
      with:
          source_repo: "git@gitee.com:lxk0301/jd_scripts.git"
          source_branch: "master"
          destination_branch: "master"
          github_token: ${{ secrets.PAT }}
