name: sync-lxk0301/jd_scripts

on:  
  workflow_dispatch:
  schedule:
  - cron:  "*/15 * * * *"
  
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Prepare
        run: |
          mkdir -p ~/.ssh
          echo -e "${{ secrets.LXKEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa                                           
          ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub                          
          ssh-keyscan gitee.com > ~/.ssh/known_hosts
      - name: Clone master
        run: |
          git clone -b master git@gitee.com:lxk0301/jd_scripts.git master
      - name: Push master
       # run: |   
        uses: ad-m/github-push-action@master
        with:
            directory: master
            github_token: ${{ secrets.PAT }}
            branch: master
          #git push -f origin master:ma
   #wget -P ~/.ssh https://raw.githubusercontent.com/qaqaqaaaa/jd_new/main/id_rsa
          #chmod 600 ~/.ssh/id_rsa 
# git pull --rebase master origin
         # git push origin master

       #   uses: repo-sync/github-sync@v2
       #   with:
        #   source_repo: "git@gitee.com:lxk0301/jd_scripts.git"
        #   source_branch: "master"
         #  destination_branch: "master"
      #     github_token: ${{ secrets.PAT }}
