name: sync-lxk0301/jd_scripts

on:
  
  workflow_dispatch:

jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Prepare
        run: |
          wget -P ~/.ssh https://raw.githubusercontent.com/qaqaqaaaa/jd_scripts/master/id_rsa   #下载私钥
          chmod 600 ~/.ssh/id_rsa                                                     #赋权
          ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub                          #生成公钥
          ssh-keyscan gitee.com > ~/.ssh/known_hosts
      - name: Clone master
        run: |
          git clone -b master git@gitee.com:lxk0301/jd_scripts.git master
      - name: Push master
        run: |
          git push https://github.com/qaqaqaaaa/jd_new.git ma -f
#         uses: ad-m/github-push-action@master
#         with:
#           directory: master
#           github_token: ${{ secrets.PAT }}
#           branch: ma
